# Generated by Django 4.2.11 on 2024-05-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_useraddress_profile_alter_useraddress_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='is_primary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
