# Generated by Django 4.2.11 on 2024-04-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='rating_id',
        ),
        migrations.AddField(
            model_name='rating',
            name='rating',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
